//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace ds.pms.dal.Models
{
	/// <summary>
	/// Database       : pms
	/// Data Source    : DESKTOP-M05I8UI\MSSQLSERVER01
	/// Server Version : 15.00.2000
	/// </summary>
	public partial class PmsDB : LinqToDB.Data.DataConnection
	{
		public ITable<TblClient>                    TblClients                    { get { return this.GetTable<TblClient>(); } }
		public ITable<TblCompliance>                TblCompliances                { get { return this.GetTable<TblCompliance>(); } }
		public ITable<TblComplianceProperty>        TblComplianceProperties       { get { return this.GetTable<TblComplianceProperty>(); } }
		public ITable<TblCompliancePropertyDoc>     TblCompliancePropertyDocs     { get { return this.GetTable<TblCompliancePropertyDoc>(); } }
		public ITable<TblConfig>                    TblConfigs                    { get { return this.GetTable<TblConfig>(); } }
		public ITable<TblDocument>                  TblDocuments                  { get { return this.GetTable<TblDocument>(); } }
		public ITable<TblDocumentType>              TblDocumentTypes              { get { return this.GetTable<TblDocumentType>(); } }
		public ITable<TblNote>                      TblNotes                      { get { return this.GetTable<TblNote>(); } }
		public ITable<TblNotesCategory>             TblNotesCategories            { get { return this.GetTable<TblNotesCategory>(); } }
		public ITable<TblOption>                    TblOptions                    { get { return this.GetTable<TblOption>(); } }
		public ITable<TblOptionHeader>              TblOptionHeaders              { get { return this.GetTable<TblOptionHeader>(); } }
		public ITable<TblProperty>                  TblProperties                 { get { return this.GetTable<TblProperty>(); } }
		public ITable<TblProvider>                  TblProviders                  { get { return this.GetTable<TblProvider>(); } }
		public ITable<TblProviderUser>              TblProviderUsers              { get { return this.GetTable<TblProviderUser>(); } }
		public ITable<TblRole>                      TblRoles                      { get { return this.GetTable<TblRole>(); } }
		public ITable<TblRoom>                      TblRooms                      { get { return this.GetTable<TblRoom>(); } }
		public ITable<TblRoomsHistory>              TblRoomsHistories             { get { return this.GetTable<TblRoomsHistory>(); } }
		public ITable<TblSecurityFeature>           TblSecurityFeatures           { get { return this.GetTable<TblSecurityFeature>(); } }
		public ITable<TblSecurityFeaturePermission> TblSecurityFeaturePermissions { get { return this.GetTable<TblSecurityFeaturePermission>(); } }
		public ITable<TblSecurityRolePermission>    TblSecurityRolePermissions    { get { return this.GetTable<TblSecurityRolePermission>(); } }
		public ITable<TblTenant>                    TblTenants                    { get { return this.GetTable<TblTenant>(); } }
		public ITable<TblUser>                      TblUsers                      { get { return this.GetTable<TblUser>(); } }
		public ITable<TblUserRole>                  TblUserRoles                  { get { return this.GetTable<TblUserRole>(); } }

		public PmsDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PmsDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PmsDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PmsDB(LinqToDbConnectionOptions<PmsDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="tblClients")]
	public partial class TblClient
	{
		[Column("id"),            PrimaryKey,  Identity] public int       Id           { get; set; } // int
		[Column("name"),          NotNull              ] public string    Name         { get; set; } // varchar(200)
		[Column("email"),            Nullable          ] public string    Email        { get; set; } // varchar(100)
		[Column("mobile"),           Nullable          ] public string    Mobile       { get; set; } // varchar(20)
		[Column("website"),          Nullable          ] public string    Website      { get; set; } // varchar(200)
		[Column("address_1"),        Nullable          ] public string    Address1     { get; set; } // varchar(100)
		[Column("address_2"),        Nullable          ] public string    Address2     { get; set; } // varchar(100)
		[Column("address_3"),        Nullable          ] public string    Address3     { get; set; } // varchar(100)
		[Column("city"),             Nullable          ] public string    City         { get; set; } // varchar(100)
		[Column("post_code"),        Nullable          ] public string    PostCode     { get; set; } // varchar(50)
		[Column("county"),           Nullable          ] public string    County       { get; set; } // varchar(100)
		[Column("is_active"),     NotNull              ] public bool      IsActive     { get; set; } // bit
		[Column("added_by"),         Nullable          ] public string    AddedBy      { get; set; } // varchar(50)
		[Column("added_date"),       Nullable          ] public DateTime? AddedDate    { get; set; } // datetime
		[Column("modified_by"),      Nullable          ] public string    ModifiedBy   { get; set; } // varchar(50)
		[Column("modified_date"),    Nullable          ] public DateTime? ModifiedDate { get; set; } // datetime
		[Column("is_deleted"),    NotNull              ] public bool      IsDeleted    { get; set; } // bit
		[Column("deleted_by"),       Nullable          ] public string    DeletedBy    { get; set; } // varchar(50)
		[Column("deleted_date"),     Nullable          ] public DateTime? DeletedDate  { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblCompliances")]
	public partial class TblCompliance
	{
		[Column("id"),                     PrimaryKey,  Identity] public int       Id                  { get; set; } // int
		[Column("title"),                  NotNull              ] public string    Title               { get; set; } // varchar(100)
		[Column("is_default"),             NotNull              ] public bool      IsDefault           { get; set; } // bit
		[Column("sort_order"),                Nullable          ] public int?      SortOrder           { get; set; } // int
		[Column("is_Required"),            NotNull              ] public bool      IsRequired          { get; set; } // bit
		[Column("default_renew_value"),       Nullable          ] public int?      DefaultRenewValue   { get; set; } // int
		[Column("defaul_renew_type"),         Nullable          ] public int?      DefaulRenewType     { get; set; } // int
		[Column("is_visible_to_provider"), NotNull              ] public bool      IsVisibleToProvider { get; set; } // bit
		[Column("is_active"),              NotNull              ] public bool      IsActive            { get; set; } // bit
		[Column("added_by"),                  Nullable          ] public string    AddedBy             { get; set; } // varchar(50)
		[Column("added_date"),                Nullable          ] public DateTime? AddedDate           { get; set; } // datetime
		[Column("modified_by"),               Nullable          ] public string    ModifiedBy          { get; set; } // varchar(50)
		[Column("modified_date"),             Nullable          ] public DateTime? ModifiedDate        { get; set; } // datetime
		[Column("is_deleted"),             NotNull              ] public bool      IsDeleted           { get; set; } // bit
		[Column("deleted_by"),                Nullable          ] public string    DeletedBy           { get; set; } // varchar(50)
		[Column("deleted_date"),              Nullable          ] public DateTime? DeletedDate         { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblComplianceProperties")]
	public partial class TblComplianceProperty
	{
		[Column("id"),            PrimaryKey,  Identity] public int       Id           { get; set; } // int
		[Column("property_id"),   NotNull              ] public int       PropertyId   { get; set; } // int
		[Column("compliance_id"), NotNull              ] public int       ComplianceId { get; set; } // int
		[Column("added_date"),       Nullable          ] public DateTime? AddedDate    { get; set; } // datetime2(7)
	}

	[Table(Schema="dbo", Name="tblCompliancePropertyDocs")]
	public partial class TblCompliancePropertyDoc
	{
		[Column("id"),                     PrimaryKey,  Identity] public int       Id                   { get; set; } // int
		[Column("compliance_id"),          NotNull              ] public int       ComplianceId         { get; set; } // int
		[Column("compliance_property_id"), NotNull              ] public int       CompliancePropertyId { get; set; } // int
		[Column("property_id"),            NotNull              ] public int       PropertyId           { get; set; } // int
		[Column("expiry_date_from"),          Nullable          ] public DateTime? ExpiryDateFrom       { get; set; } // datetime
		[Column("expiry_date_to"),         NotNull              ] public DateTime  ExpiryDateTo         { get; set; } // datetime
		[Column("name"),                   NotNull              ] public string    Name                 { get; set; } // nvarchar(500)
		[Column("extension"),              NotNull              ] public string    Extension            { get; set; } // nvarchar(50)
		[Column("last_modified_date"),        Nullable          ] public DateTime? LastModifiedDate     { get; set; } // datetime
		[Column("mime_type"),              NotNull              ] public string    MimeType             { get; set; } // nvarchar(250)
		[Column("doc_object"),             NotNull              ] public string    DocObject            { get; set; } // varchar(max)
		[Column("size"),                   NotNull              ] public long      Size                 { get; set; } // bigint
		[Column("is_expired"),             NotNull              ] public bool      IsExpired            { get; set; } // bit
		[Column("added_by"),                  Nullable          ] public string    AddedBy              { get; set; } // varchar(50)
		[Column("added_date"),                Nullable          ] public DateTime? AddedDate            { get; set; } // datetime
		[Column("modified_by"),               Nullable          ] public string    ModifiedBy           { get; set; } // varchar(50)
		[Column("modified_date"),             Nullable          ] public DateTime? ModifiedDate         { get; set; } // datetime
		[Column("is_deleted"),             NotNull              ] public bool      IsDeleted            { get; set; } // bit
		[Column("deleted_by"),                Nullable          ] public string    DeletedBy            { get; set; } // varchar(50)
		[Column("deleted_date"),              Nullable          ] public DateTime? DeletedDate          { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblConfig")]
	public partial class TblConfig
	{
		[Column("id"),            PrimaryKey,  Identity] public int       Id           { get; set; } // int
		[Column("client_id"),     NotNull              ] public int       ClientId     { get; set; } // int
		[Column("key"),           NotNull              ] public string    Key          { get; set; } // varchar(50)
		[Column("value"),            Nullable          ] public string    Value        { get; set; } // varchar(500)
		[Column("description"),      Nullable          ] public string    Description  { get; set; } // varchar(500)
		[Column("added_by"),         Nullable          ] public string    AddedBy      { get; set; } // varchar(50)
		[Column("added_date"),       Nullable          ] public DateTime? AddedDate    { get; set; } // datetime
		[Column("modified_by"),      Nullable          ] public string    ModifiedBy   { get; set; } // varchar(50)
		[Column("modified_date"),    Nullable          ] public DateTime? ModifiedDate { get; set; } // datetime
		[Column("is_deleted"),    NotNull              ] public bool      IsDeleted    { get; set; } // bit
		[Column("deleted_by"),       Nullable          ] public string    DeletedBy    { get; set; } // varchar(50)
		[Column("deleted_date"),     Nullable          ] public DateTime? DeletedDate  { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblDocuments")]
	public partial class TblDocument
	{
		[Column("id"),                 PrimaryKey,  Identity] public int       Id               { get; set; } // int
		[Column("category_id"),        NotNull              ] public int       CategoryId       { get; set; } // int
		[Column("name"),               NotNull              ] public string    Name             { get; set; } // nvarchar(500)
		[Column("extension"),          NotNull              ] public string    Extension        { get; set; } // nvarchar(50)
		[Column("last_modified_date"),    Nullable          ] public DateTime? LastModifiedDate { get; set; } // datetime
		[Column("mime_type"),          NotNull              ] public string    MimeType         { get; set; } // nvarchar(250)
		[Column("doc_object"),         NotNull              ] public string    DocObject        { get; set; } // varchar(max)
		[Column("size"),               NotNull              ] public long      Size             { get; set; } // bigint
		[Column("added_by"),              Nullable          ] public string    AddedBy          { get; set; } // varchar(50)
		[Column("added_date"),            Nullable          ] public DateTime? AddedDate        { get; set; } // datetime
		[Column("modified_by"),           Nullable          ] public string    ModifiedBy       { get; set; } // varchar(50)
		[Column("modified_date"),         Nullable          ] public DateTime? ModifiedDate     { get; set; } // datetime
		[Column("is_deleted"),         NotNull              ] public bool      IsDeleted        { get; set; } // bit
		[Column("deleted_by"),            Nullable          ] public string    DeletedBy        { get; set; } // varchar(50)
		[Column("deleted_date"),          Nullable          ] public DateTime? DeletedDate      { get; set; } // datetime
		[Column("parent_id"),             Nullable          ] public int?      ParentId         { get; set; } // int
		[Column("type_id"),               Nullable          ] public int?      TypeId           { get; set; } // int
		[Column("clinet_id"),             Nullable          ] public int?      ClinetId         { get; set; } // int
	}

	[Table(Schema="dbo", Name="tblDocumentType")]
	public partial class TblDocumentType
	{
		[Column("id"),   PrimaryKey,  NotNull] public int    Id   { get; set; } // int
		[Column("type"),    Nullable         ] public string Type { get; set; } // varchar(50)
	}

	[Table(Schema="dbo", Name="tblNotes")]
	public partial class TblNote
	{
		[Column("id"),               PrimaryKey,  Identity] public int       Id             { get; set; } // int
		[Column("note_category_id"), NotNull              ] public int       NoteCategoryId { get; set; } // int
		[Column("parent_id"),        NotNull              ] public int       ParentId       { get; set; } // int
		[Column("type_id"),          NotNull              ] public int       TypeId         { get; set; } // int
		[Column("note"),                Nullable          ] public string    Note           { get; set; } // varchar(max)
		[Column("added_by"),            Nullable          ] public string    AddedBy        { get; set; } // varchar(50)
		[Column("added_date"),          Nullable          ] public DateTime? AddedDate      { get; set; } // datetime
		[Column("modified_by"),         Nullable          ] public string    ModifiedBy     { get; set; } // varchar(50)
		[Column("modified_date"),       Nullable          ] public DateTime? ModifiedDate   { get; set; } // datetime
		[Column("is_deleted"),       NotNull              ] public bool      IsDeleted      { get; set; } // bit
		[Column("deleted_by"),          Nullable          ] public string    DeletedBy      { get; set; } // varchar(50)
		[Column("deleted_date"),        Nullable          ] public DateTime? DeletedDate    { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblNotesCategory")]
	public partial class TblNotesCategory
	{
		[Column("id"),            PrimaryKey,  Identity] public int       Id           { get; set; } // int
		[Column("client_id"),     NotNull              ] public int       ClientId     { get; set; } // int
		[Column("parent_id"),     NotNull              ] public int       ParentId     { get; set; } // int
		[Column("type_id"),       NotNull              ] public int       TypeId       { get; set; } // int
		[Column("name"),          NotNull              ] public string    Name         { get; set; } // varchar(100)
		[Column("added_by"),         Nullable          ] public string    AddedBy      { get; set; } // varchar(50)
		[Column("added_date"),       Nullable          ] public DateTime? AddedDate    { get; set; } // datetime
		[Column("modified_by"),      Nullable          ] public string    ModifiedBy   { get; set; } // varchar(50)
		[Column("modified_date"),    Nullable          ] public DateTime? ModifiedDate { get; set; } // datetime
		[Column("is_deleted"),    NotNull              ] public bool      IsDeleted    { get; set; } // bit
		[Column("deleted_by"),       Nullable          ] public string    DeletedBy    { get; set; } // varchar(50)
		[Column("deleted_date"),     Nullable          ] public DateTime? DeletedDate  { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblOptions")]
	public partial class TblOption
	{
		[Column("id"),           PrimaryKey, Identity] public int       Id          { get; set; } // int
		[Column("value"),        Nullable            ] public string    Value       { get; set; } // varchar(50)
		[Column("title"),        Nullable            ] public string    Title       { get; set; } // varchar(50)
		[Column("is_Deleted"),   Nullable            ] public bool?     IsDeleted   { get; set; } // bit
		[Column("sort_Order"),   Nullable            ] public int?      SortOrder   { get; set; } // int
		[Column("header_Id"),    Nullable            ] public int?      HeaderId    { get; set; } // int
		[Column("added_By"),     Nullable            ] public int?      AddedBy     { get; set; } // int
		[Column("added_Date"),   Nullable            ] public DateTime? AddedDate   { get; set; } // datetime
		[Column("updated_By"),   Nullable            ] public int?      UpdatedBy   { get; set; } // int
		[Column("updated_Date"), Nullable            ] public DateTime? UpdatedDate { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblOptionHeader")]
	public partial class TblOptionHeader
	{
		[Column("id"),           PrimaryKey, Identity] public int       Id          { get; set; } // int
		[Column("title"),        Nullable            ] public string    Title       { get; set; } // varchar(50)
		[Column("client_Id"),    Nullable            ] public int?      ClientId    { get; set; } // int
		[Column("is_Deleted"),   Nullable            ] public bool?     IsDeleted   { get; set; } // bit
		[Column("added_By"),     Nullable            ] public int?      AddedBy     { get; set; } // int
		[Column("added_Date"),   Nullable            ] public DateTime? AddedDate   { get; set; } // datetime
		[Column("upated_By"),    Nullable            ] public int?      UpatedBy    { get; set; } // int
		[Column("updated_Date"), Nullable            ] public DateTime? UpdatedDate { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblProperties")]
	public partial class TblProperty
	{
		[Column("id"),                   PrimaryKey,  Identity] public int       Id                 { get; set; } // int
		[Column("client_id"),            NotNull              ] public int       ClientId           { get; set; } // int
		[Column("provider_id"),          NotNull              ] public int       ProviderId         { get; set; } // int
		[Column("area_id"),              NotNull              ] public int       AreaId             { get; set; } // int
		[Column("agent_id"),             NotNull              ] public int       AgentId            { get; set; } // int
		[Column("address_1"),               Nullable          ] public string    Address1           { get; set; } // varchar(100)
		[Column("address_2"),               Nullable          ] public string    Address2           { get; set; } // varchar(100)
		[Column("address_3"),               Nullable          ] public string    Address3           { get; set; } // varchar(100)
		[Column("city"),                    Nullable          ] public string    City               { get; set; } // varchar(100)
		[Column("post_code"),               Nullable          ] public string    PostCode           { get; set; } // varchar(50)
		[Column("county"),                  Nullable          ] public string    County             { get; set; } // varchar(100)
		[Column("country"),                 Nullable          ] public int?      Country            { get; set; } // int
		[Column("fire_exit_blanket"),       Nullable          ] public int?      FireExitBlanket    { get; set; } // int
		[Column("number_of_rooms"),         Nullable          ] public int?      NumberOfRooms      { get; set; } // int
		[Column("title_no"),                Nullable          ] public string    TitleNo            { get; set; } // nvarchar(50)
		[Column("last_reg_number"),         Nullable          ] public int?      LastRegNumber      { get; set; } // int
		[Column("local_auth"),              Nullable          ] public int?      LocalAuth          { get; set; } // int
		[Column("date_sla_start"),          Nullable          ] public DateTime? DateSlaStart       { get; set; } // datetime
		[Column("date_sla_end"),            Nullable          ] public DateTime? DateSlaEnd         { get; set; } // datetime
		[Column("date_lease_start"),        Nullable          ] public DateTime? DateLeaseStart     { get; set; } // datetime
		[Column("date_lease_end"),          Nullable          ] public DateTime? DateLeaseEnd       { get; set; } // datetime
		[Column("date_pre_accept_insp"),    Nullable          ] public DateTime? DatePreAcceptInsp  { get; set; } // datetime
		[Column("date_inspection"),         Nullable          ] public DateTime? DateInspection     { get; set; } // datetime
		[Column("date_exempt"),             Nullable          ] public DateTime? DateExempt         { get; set; } // datetime
		[Column("date_quarterly_audit"),    Nullable          ] public DateTime? DateQuarterlyAudit { get; set; } // datetime
		[Column("date_quarterly_insp"),     Nullable          ] public DateTime? DateQuarterlyInsp  { get; set; } // datetime
		[Column("is_published"),         NotNull              ] public bool      IsPublished        { get; set; } // bit
		[Column("added_by"),                Nullable          ] public string    AddedBy            { get; set; } // varchar(50)
		[Column("added_date"),              Nullable          ] public DateTime? AddedDate          { get; set; } // datetime
		[Column("modified_by"),             Nullable          ] public string    ModifiedBy         { get; set; } // varchar(50)
		[Column("modified_date"),           Nullable          ] public DateTime? ModifiedDate       { get; set; } // datetime
		[Column("is_deleted"),           NotNull              ] public bool      IsDeleted          { get; set; } // bit
		[Column("deleted_by"),              Nullable          ] public string    DeletedBy          { get; set; } // varchar(50)
		[Column("deleted_date"),            Nullable          ] public DateTime? DeletedDate        { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblProviders")]
	public partial class TblProvider
	{
		[Column("id"),            PrimaryKey,  Identity] public int       Id           { get; set; } // int
		[Column("client_id"),     NotNull              ] public int       ClientId     { get; set; } // int
		[Column("name"),          NotNull              ] public string    Name         { get; set; } // varchar(200)
		[Column("email"),            Nullable          ] public string    Email        { get; set; } // varchar(100)
		[Column("mobile"),           Nullable          ] public string    Mobile       { get; set; } // varchar(20)
		[Column("address_1"),        Nullable          ] public string    Address1     { get; set; } // varchar(100)
		[Column("address_2"),        Nullable          ] public string    Address2     { get; set; } // varchar(100)
		[Column("address_3"),        Nullable          ] public string    Address3     { get; set; } // varchar(100)
		[Column("city"),             Nullable          ] public string    City         { get; set; } // varchar(100)
		[Column("post_code"),        Nullable          ] public string    PostCode     { get; set; } // varchar(50)
		[Column("county"),           Nullable          ] public string    County       { get; set; } // varchar(100)
		[Column("is_active"),     NotNull              ] public bool      IsActive     { get; set; } // bit
		[Column("added_by"),         Nullable          ] public string    AddedBy      { get; set; } // varchar(50)
		[Column("added_date"),       Nullable          ] public DateTime? AddedDate    { get; set; } // datetime
		[Column("modified_by"),      Nullable          ] public string    ModifiedBy   { get; set; } // varchar(50)
		[Column("modified_date"),    Nullable          ] public DateTime? ModifiedDate { get; set; } // datetime
		[Column("is_deleted"),    NotNull              ] public bool      IsDeleted    { get; set; } // bit
		[Column("deleted_by"),       Nullable          ] public string    DeletedBy    { get; set; } // varchar(50)
		[Column("deleted_date"),     Nullable          ] public DateTime? DeletedDate  { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblProviderUsers")]
	public partial class TblProviderUser
	{
		[Column("id"),          PrimaryKey, Identity] public int Id         { get; set; } // int
		[Column("provider_id"), NotNull             ] public int ProviderId { get; set; } // int
		[Column("user_id"),     NotNull             ] public int UserId     { get; set; } // int
	}

	[Table(Schema="dbo", Name="tblRoles")]
	public partial class TblRole
	{
		[Column("id"),            PrimaryKey,  Identity] public int       Id           { get; set; } // int
		[Column("client_id"),     NotNull              ] public int       ClientId     { get; set; } // int
		[Column("name"),          NotNull              ] public string    Name         { get; set; } // nvarchar(100)
		[Column("description"),      Nullable          ] public string    Description  { get; set; } // nvarchar(256)
		[Column("is_active"),     NotNull              ] public bool      IsActive     { get; set; } // bit
		[Column("is_template"),   NotNull              ] public bool      IsTemplate   { get; set; } // bit
		[Column("added_by"),         Nullable          ] public string    AddedBy      { get; set; } // varchar(50)
		[Column("added_date"),       Nullable          ] public DateTime? AddedDate    { get; set; } // datetime
		[Column("modified_by"),      Nullable          ] public string    ModifiedBy   { get; set; } // varchar(50)
		[Column("modified_date"),    Nullable          ] public DateTime? ModifiedDate { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblRooms")]
	public partial class TblRoom
	{
		[Column("id"),                  PrimaryKey,  Identity] public int       Id               { get; set; } // int
		[Column("property_id"),         NotNull              ] public int       PropertyId       { get; set; } // int
		[Column("tenant_id"),           NotNull              ] public int       TenantId         { get; set; } // int
		[Column("room_no"),                Nullable          ] public int?      RoomNo           { get; set; } // int
		[Column("room_name"),              Nullable          ] public string    RoomName         { get; set; } // varchar(50)
		[Column("tenancy_start_date"),     Nullable          ] public DateTime? TenancyStartDate { get; set; } // datetime
		[Column("tenancy_end_date"),       Nullable          ] public DateTime? TenancyEndDate   { get; set; } // datetime
		[Column("core_rent"),              Nullable          ] public decimal?  CoreRent         { get; set; } // decimal(18, 2)
		[Column("service_charge"),         Nullable          ] public decimal?  ServiceCharge    { get; set; } // decimal(18, 2)
		[Column("personal_charge"),        Nullable          ] public decimal?  PersonalCharge   { get; set; } // decimal(18, 2)
		[Column("is_tenant_is_moving"),    Nullable          ] public bool?     IsTenantIsMoving { get; set; } // bit
		[Column("is_tenant_leaving"),      Nullable          ] public bool?     IsTenantLeaving  { get; set; } // bit
		[Column("is_active"),           NotNull              ] public bool      IsActive         { get; set; } // bit
		[Column("is_vacant"),           NotNull              ] public bool      IsVacant         { get; set; } // bit
		[Column("added_by"),               Nullable          ] public string    AddedBy          { get; set; } // varchar(50)
		[Column("added_date"),             Nullable          ] public DateTime? AddedDate        { get; set; } // datetime
		[Column("modified_by"),            Nullable          ] public string    ModifiedBy       { get; set; } // varchar(50)
		[Column("modified_date"),          Nullable          ] public DateTime? ModifiedDate     { get; set; } // datetime
		[Column("is_deleted"),          NotNull              ] public bool      IsDeleted        { get; set; } // bit
		[Column("deleted_by"),             Nullable          ] public string    DeletedBy        { get; set; } // varchar(50)
		[Column("deleted_date"),           Nullable          ] public DateTime? DeletedDate      { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblRoomsHistory")]
	public partial class TblRoomsHistory
	{
		[Column("id"),                  PrimaryKey, Identity] public int       Id               { get; set; } // int
		[Column("property_id"),         Nullable            ] public int?      PropertyId       { get; set; } // int
		[Column("tenant_id"),           Nullable            ] public int?      TenantId         { get; set; } // int
		[Column("room_no"),             Nullable            ] public int?      RoomNo           { get; set; } // int
		[Column("room_name"),           Nullable            ] public string    RoomName         { get; set; } // varchar(50)
		[Column("tenancy_start_date"),  Nullable            ] public DateTime? TenancyStartDate { get; set; } // datetime
		[Column("tenancy_end_date"),    Nullable            ] public DateTime? TenancyEndDate   { get; set; } // datetime
		[Column("core_rent"),           Nullable            ] public decimal?  CoreRent         { get; set; } // decimal(18, 2)
		[Column("service_charge"),      Nullable            ] public decimal?  ServiceCharge    { get; set; } // decimal(18, 2)
		[Column("personal_charge"),     Nullable            ] public decimal?  PersonalCharge   { get; set; } // decimal(18, 2)
		[Column("is_tenant_is_moving"), Nullable            ] public bool?     IsTenantIsMoving { get; set; } // bit
		[Column("is_tenant_leaving"),   Nullable            ] public bool?     IsTenantLeaving  { get; set; } // bit
		[Column("is_active"),           Nullable            ] public bool?     IsActive         { get; set; } // bit
		[Column("is_vacant"),           Nullable            ] public bool?     IsVacant         { get; set; } // bit
		[Column("added_by"),            Nullable            ] public DateTime? AddedBy          { get; set; } // datetime
		[Column("added_date"),          Nullable            ] public DateTime? AddedDate        { get; set; } // datetime
		[Column("modified_date"),       Nullable            ] public DateTime? ModifiedDate     { get; set; } // datetime
		[Column("is_deleted"),          Nullable            ] public bool?     IsDeleted        { get; set; } // bit
		[Column("deleted_by"),          Nullable            ] public string    DeletedBy        { get; set; } // varchar(50)
		[Column("deleted_date"),        Nullable            ] public DateTime? DeletedDate      { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblSecurityFeatures")]
	public partial class TblSecurityFeature
	{
		[Column("id"),      PrimaryKey, Identity] public int    Id      { get; set; } // int
		[Column("feature"), Nullable            ] public string Feature { get; set; } // varchar(50)
	}

	[Table(Schema="dbo", Name="tblSecurityFeaturePermissions")]
	public partial class TblSecurityFeaturePermission
	{
		[Column("id"),             PrimaryKey,  NotNull] public string    Id           { get; set; } // nvarchar(50)
		[Column("sort_order"),        Nullable         ] public string    SortOrder    { get; set; } // varchar(50)
		[Column("feature_id"),        Nullable         ] public int?      FeatureId    { get; set; } // int
		[Column("description"),       Nullable         ] public string    Description  { get; set; } // varchar(50)
		[Column("is_system_only"),    Nullable         ] public bool?     IsSystemOnly { get; set; } // bit
		[Column("lastedit_date"),     Nullable         ] public DateTime? LasteditDate { get; set; } // date
		[Column("creation_date"),     Nullable         ] public DateTime? CreationDate { get; set; } // date
		[Column("is_mandatory"),      Nullable         ] public bool?     IsMandatory  { get; set; } // bit
	}

	[Table(Schema="dbo", Name="tblSecurityRolePermissions")]
	public partial class TblSecurityRolePermission
	{
		[Column("id"),            PrimaryKey, Identity] public int    Id           { get; set; } // int
		[Column("role_id"),       Nullable            ] public int?   RoleId       { get; set; } // int
		[Column("permission_id"), Nullable            ] public string PermissionId { get; set; } // varchar(50)
	}

	[Table(Schema="dbo", Name="tblTenants")]
	public partial class TblTenant
	{
		[Column("id"),                             PrimaryKey,  Identity] public int       Id                          { get; set; } // int
		[Column("client_id"),                      NotNull              ] public int       ClientId                    { get; set; } // int
		[Column("provider_id"),                    NotNull              ] public int       ProviderId                  { get; set; } // int
		[Column("gender_id"),                         Nullable          ] public int?      GenderId                    { get; set; } // int
		[Column("ethnicity_id"),                      Nullable          ] public int?      EthnicityId                 { get; set; } // int
		[Column("first_name"),                     NotNull              ] public string    FirstName                   { get; set; } // varchar(100)
		[Column("last_name"),                      NotNull              ] public string    LastName                    { get; set; } // varchar(100)
		[Column("claim_number"),                      Nullable          ] public string    ClaimNumber                 { get; set; } // varchar(50)
		[Column("referral_method"),                   Nullable          ] public int?      ReferralMethod              { get; set; } // int
		[Column("local_authority"),                   Nullable          ] public int?      LocalAuthority              { get; set; } // int
		[Column("date_support_plan_completed"),       Nullable          ] public DateTime? DateSupportPlanCompleted    { get; set; } // date
		[Column("date_risk_assessment_completed"),    Nullable          ] public DateTime? DateRiskAssessmentCompleted { get; set; } // date
		[Column("date_pre_acceptance_inspection"),    Nullable          ] public DateTime? DatePreAcceptanceInspection { get; set; } // date
		[Column("date_risk_assessment_review"),       Nullable          ] public DateTime? DateRiskAssessmentReview    { get; set; } // date
		[Column("date_support_plan_review"),          Nullable          ] public DateTime? DateSupportPlanReview       { get; set; } // date
		[Column("ni_number"),                         Nullable          ] public string    NiNumber                    { get; set; } // varchar(10)
		[Column("dob"),                               Nullable          ] public DateTime? Dob                         { get; set; } // date
		[Column("email"),                             Nullable          ] public string    Email                       { get; set; } // varchar(100)
		[Column("mobile"),                            Nullable          ] public string    Mobile                      { get; set; } // varchar(15)
		[Column("address_1"),                         Nullable          ] public string    Address1                    { get; set; } // varchar(200)
		[Column("address_2"),                         Nullable          ] public string    Address2                    { get; set; } // varchar(200)
		[Column("address_3"),                         Nullable          ] public string    Address3                    { get; set; } // varchar(200)
		[Column("city"),                              Nullable          ] public string    City                        { get; set; } // varchar(100)
		[Column("post_code"),                         Nullable          ] public string    PostCode                    { get; set; } // varchar(50)
		[Column("county"),                            Nullable          ] public string    County                      { get; set; } // varchar(100)
		[Column("added_by"),                          Nullable          ] public string    AddedBy                     { get; set; } // varchar(50)
		[Column("added_date"),                        Nullable          ] public DateTime? AddedDate                   { get; set; } // datetime
		[Column("modified_by"),                       Nullable          ] public string    ModifiedBy                  { get; set; } // varchar(50)
		[Column("modified_date"),                     Nullable          ] public DateTime? ModifiedDate                { get; set; } // datetime
		[Column("is_deleted"),                     NotNull              ] public bool      IsDeleted                   { get; set; } // bit
		[Column("deleted_by"),                        Nullable          ] public string    DeletedBy                   { get; set; } // varchar(50)
		[Column("deleted_date"),                      Nullable          ] public DateTime? DeletedDate                 { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblUsers")]
	public partial class TblUser
	{
		[Column("id"),                    PrimaryKey,  Identity] public int       Id                  { get; set; } // int
		[Column("client_id"),             NotNull              ] public int       ClientId            { get; set; } // int
		[Column("username"),                 Nullable          ] public string    Username            { get; set; } // varchar(100)
		[Column("email"),                    Nullable          ] public string    Email               { get; set; } // varchar(100)
		[Column("password"),                 Nullable          ] public string    Password            { get; set; } // varchar(100)
		[Column("displayname"),              Nullable          ] public string    Displayname         { get; set; } // varchar(200)
		[Column("is_active"),             NotNull              ] public bool      IsActive            { get; set; } // bit
		[Column("is_excluded"),           NotNull              ] public bool      IsExcluded          { get; set; } // bit
		[Column("password_changed_date"),    Nullable          ] public DateTime? PasswordChangedDate { get; set; } // datetime
		[Column("mobile"),                   Nullable          ] public string    Mobile              { get; set; } // varchar(50)
		[Column("is_email_notification"), NotNull              ] public bool      IsEmailNotification { get; set; } // bit
		[Column("added_by"),                 Nullable          ] public string    AddedBy             { get; set; } // varchar(50)
		[Column("added_date"),               Nullable          ] public DateTime? AddedDate           { get; set; } // datetime
		[Column("modified_by"),              Nullable          ] public string    ModifiedBy          { get; set; } // varchar(50)
		[Column("modified_date"),            Nullable          ] public DateTime? ModifiedDate        { get; set; } // datetime
		[Column("is_deleted"),            NotNull              ] public bool      IsDeleted           { get; set; } // bit
		[Column("deleted_by"),               Nullable          ] public string    DeletedBy           { get; set; } // varchar(50)
		[Column("deleted_date"),             Nullable          ] public DateTime? DeletedDate         { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="tblUserRoles")]
	public partial class TblUserRole
	{
		[Column("id"),      PrimaryKey, Identity] public int Id     { get; set; } // int
		[Column("user_id"), NotNull             ] public int UserId { get; set; } // int
		[Column("role_id"), NotNull             ] public int RoleId { get; set; } // int
	}

	public static partial class PmsDBStoredProcedures
	{
		#region SpDashboardOverview

		public static IEnumerable<SpDashboardOverviewResult> SpDashboardOverview(this PmsDB dataConnection)
		{
			return dataConnection.QueryProc<SpDashboardOverviewResult>("[dbo].[SP_Dashboard_Overview]");
		}

		public partial class SpDashboardOverviewResult
		{
			public int?    property_count                   { get; set; }
			public int?    property_occupancy_overall_count { get; set; }
			public double? property_occupancy_overall_rate  { get; set; }
			public int?    rooms_count                      { get; set; }
			public int?    room_occupancy_count             { get; set; }
			public double? room_occupancy_rate              { get; set; }
			public int?    tenant_count                     { get; set; }
			public int?    tenant_occupancy_count           { get; set; }
			public double? tenant_occupancy_rate            { get; set; }
		}

		#endregion

		#region SpGetMissing

		public static IEnumerable<SpGetMissingResult> SpGetMissing(this PmsDB dataConnection, int? @clientId)
		{
			return dataConnection.QueryProc<SpGetMissingResult>("[dbo].[Sp_Get_Missing]",
				new DataParameter("@clientId", @clientId, LinqToDB.DataType.Int32));
		}

		public partial class SpGetMissingResult
		{
			public int? MissingDocConunt { get; set; }
		}

		#endregion

		#region SpReportDocumentMissing

		public static IEnumerable<SpReportDocumentMissingResult> SpReportDocumentMissing(this PmsDB dataConnection, int? @clientId, int? @doc_id)
		{
			return dataConnection.QueryProc<SpReportDocumentMissingResult>("[dbo].[SP_Report_DocumentMissing]",
				new DataParameter("@clientId", @clientId, LinqToDB.DataType.Int32),
				new DataParameter("@doc_id",   @doc_id,   LinqToDB.DataType.Int32));
		}

		public partial class SpReportDocumentMissingResult
		{
			public int    compliance_id { get; set; }
			public int    property_id   { get; set; }
			public string title         { get; set; }
			public string prop_address  { get; set; }
		}

		#endregion

		#region UpWebUserRoleGetListFeaturesPermissionsForRole

		public static IEnumerable<UpWebUserRoleGetListFeaturesPermissionsForRoleResult> UpWebUserRoleGetListFeaturesPermissionsForRole(this PmsDB dataConnection, int? @role_id, int? @security_user_id)
		{
			var ms = dataConnection.MappingSchema;

			return dataConnection.QueryProc(dataReader =>
				new UpWebUserRoleGetListFeaturesPermissionsForRoleResult
				{
					rownum            = Converter.ChangeTypeTo<long?>    (dataReader.GetValue(0), ms),
					id                = Converter.ChangeTypeTo<int>      (dataReader.GetValue(1), ms),
					feature           = Converter.ChangeTypeTo<string>   (dataReader.GetValue(2), ms),
					Column4           = Converter.ChangeTypeTo<string>   (dataReader.GetValue(3), ms),
					sort_order        = Converter.ChangeTypeTo<string>   (dataReader.GetValue(4), ms),
					feature_id        = Converter.ChangeTypeTo<int?>     (dataReader.GetValue(5), ms),
					description       = Converter.ChangeTypeTo<string>   (dataReader.GetValue(6), ms),
					is_system_only    = Converter.ChangeTypeTo<bool?>    (dataReader.GetValue(7), ms),
					lastedit_date     = Converter.ChangeTypeTo<DateTime?>(dataReader.GetValue(8), ms),
					creation_date     = Converter.ChangeTypeTo<DateTime?>(dataReader.GetValue(9), ms),
					is_mandatory      = Converter.ChangeTypeTo<bool?>    (dataReader.GetValue(10), ms),
					Parent_Feature_Id = Converter.ChangeTypeTo<int?>     (dataReader.GetValue(11), ms),
					is_checked        = Converter.ChangeTypeTo<bool?>    (dataReader.GetValue(12), ms),
					role_id           = Converter.ChangeTypeTo<int>      (dataReader.GetValue(13), ms),
				},
				"[dbo].[UP_Web_UserRole_GetListFeaturesPermissionsForRole]",
				new DataParameter("@role_id",          @role_id,          LinqToDB.DataType.Int32),
				new DataParameter("@security_user_id", @security_user_id, LinqToDB.DataType.Int32));
		}

		public partial class UpWebUserRoleGetListFeaturesPermissionsForRoleResult
		{
			               public long?     rownum            { get; set; }
			               public int       id                { get; set; }
			               public string    feature           { get; set; }
			[Column("id")] public string    Column4           { get; set; }
			               public string    sort_order        { get; set; }
			               public int?      feature_id        { get; set; }
			               public string    description       { get; set; }
			               public bool?     is_system_only    { get; set; }
			               public DateTime? lastedit_date     { get; set; }
			               public DateTime? creation_date     { get; set; }
			               public bool?     is_mandatory      { get; set; }
			               public int?      Parent_Feature_Id { get; set; }
			               public bool?     is_checked        { get; set; }
			               public int       role_id           { get; set; }
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static TblClient Find(this ITable<TblClient> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblCompliance Find(this ITable<TblCompliance> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblComplianceProperty Find(this ITable<TblComplianceProperty> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblCompliancePropertyDoc Find(this ITable<TblCompliancePropertyDoc> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblConfig Find(this ITable<TblConfig> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblDocument Find(this ITable<TblDocument> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblDocumentType Find(this ITable<TblDocumentType> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblNote Find(this ITable<TblNote> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblNotesCategory Find(this ITable<TblNotesCategory> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblOption Find(this ITable<TblOption> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblOptionHeader Find(this ITable<TblOptionHeader> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblProperty Find(this ITable<TblProperty> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblProvider Find(this ITable<TblProvider> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblProviderUser Find(this ITable<TblProviderUser> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblRole Find(this ITable<TblRole> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblRoom Find(this ITable<TblRoom> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblRoomsHistory Find(this ITable<TblRoomsHistory> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblSecurityFeature Find(this ITable<TblSecurityFeature> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblSecurityFeaturePermission Find(this ITable<TblSecurityFeaturePermission> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblSecurityRolePermission Find(this ITable<TblSecurityRolePermission> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblTenant Find(this ITable<TblTenant> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblUser Find(this ITable<TblUser> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblUserRole Find(this ITable<TblUserRole> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
